[2025-10-30T20:55:16.713+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-30T20:55:16.725+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: earthquake_pipeline.run_producer scheduled__2025-10-30T20:40:00+00:00 [queued]>
[2025-10-30T20:55:16.732+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: earthquake_pipeline.run_producer scheduled__2025-10-30T20:40:00+00:00 [queued]>
[2025-10-30T20:55:16.733+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-10-30T20:55:16.754+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_producer> on 2025-10-30 20:40:00+00:00
[2025-10-30T20:55:16.767+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'earthquake_pipeline', 'run_producer', 'scheduled__2025-10-30T20:40:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/earthquake_pipeline_dag.py', '--cfg-path', '/tmp/tmpimd00zg5']
[2025-10-30T20:55:16.769+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask run_producer
[2025-10-30T20:55:16.771+0000] {logging_mixin.py:190} WARNING - /home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=201382) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-30T20:55:16.771+0000] {standard_task_runner.py:72} INFO - Started process 201398 to run task
[2025-10-30T20:55:16.824+0000] {task_command.py:467} INFO - Running <TaskInstance: earthquake_pipeline.run_producer scheduled__2025-10-30T20:40:00+00:00 [running]> on host cs-263639028873-default
[2025-10-30T20:55:16.898+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bensha' AIRFLOW_CTX_DAG_ID='earthquake_pipeline' AIRFLOW_CTX_TASK_ID='run_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T20:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T20:40:00+00:00'
[2025-10-30T20:55:16.900+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-30T20:55:16.900+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-30T20:55:16.900+0000] {logging_mixin.py:190} INFO - Current task name:run_producer state:running start_date:2025-10-30 20:55:16.725823+00:00
[2025-10-30T20:55:16.900+0000] {logging_mixin.py:190} INFO - Dag name:earthquake_pipeline and current dag run status:running
[2025-10-30T20:55:16.901+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-10-30T20:55:16.902+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-30T20:55:16.903+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '../venv/bin/python ../producer_usgs_.py']
[2025-10-30T20:55:16.918+0000] {subprocess.py:99} INFO - Output:
[2025-10-30T20:55:16.920+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: ../venv/bin/python: No such file or directory
[2025-10-30T20:55:16.920+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-10-30T20:55:16.930+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-30T20:55:16.938+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-10-30T20:55:16.939+0000] {logging_mixin.py:190} INFO - Task start:2025-10-30 20:55:16.725823+00:00 end:2025-10-30 20:55:16.937859+00:00 duration:0.212036
[2025-10-30T20:55:16.939+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_producer> dag:<DAG: earthquake_pipeline> dagrun:<DagRun earthquake_pipeline @ 2025-10-30 20:40:00+00:00: scheduled__2025-10-30T20:40:00+00:00, state:running, queued_at: 2025-10-30 20:45:01.006770+00:00. externally triggered: False>
[2025-10-30T20:55:16.939+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-10-30T20:55:16.939+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=earthquake_pipeline, task_id=run_producer, run_id=scheduled__2025-10-30T20:40:00+00:00, execution_date=20251030T204000, start_date=20251030T205516, end_date=20251030T205516
[2025-10-30T20:55:16.978+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-10-30T20:55:16.979+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 87 for task run_producer (Bash command failed. The command returned a non-zero exit code 127.; 201398)
Traceback (most recent call last):
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bensha02019/USGov-Earthquake-Streaming-Analytics-Pipeline-GCP-Kafka-Dataflow-/venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-10-30T20:55:17.027+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-30T20:55:17.048+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-30T20:55:17.049+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
